Fire function implemented. tank shoots bullet.
peregurin/battle-tank-game pull request #2
Opened 2020-04-16 08:11 UTC by peregurin

when the tank view gets the input to fire the weapon, it calls a function in the controller. The line of communication is:-
Tankview -> tankcont -> TankSer -> BulletSer -> BulletCont -> bulletView.
Right now bullet view has the logic of firing. But this violates the MVC model. The logic needs to be in the BulletCont.
Please suggest changes so that this becomes possible.

2020-04-18 17:04 UTC, mayankgrover requested changes

2020-04-18 17:04 UTC, mayankgrover commented on Assets/_Scripts/Bullet/Bullet MVC/BulletController.cs
> +            BulletService.DestroyControllerAndModel();
use singleton

2020-04-18 17:04 UTC, mayankgrover commented on Assets/_Scripts/Bullet/Bullet MVC/BulletView.cs
> +            if((Mathf.Abs(transform.position.x) > 48f) || (Mathf.Abs(transform.position.z) > 48f)){
use collider

2020-04-18 17:04 UTC, mayankgrover commented on Assets/_Scripts/Tank/Tank MVC/TankController.cs
> +            TankView = GameObject.Instantiate<TankView>(tankView[(int)TankModel.TankType]); // now here on the basis of what the player has selected as tanktype, need to pass a variable in the tankVi
dictionary

2020-04-18 17:04 UTC, mayankgrover commented on Assets/_Scripts/Singletons/BulletService.cs
> +        public void CreateNewBullet(Vector3 position, Vector3 tankRotation)
return BC to tha tank

2020-04-20 08:13 UTC, vijit101 reviewed
- Remove all unnecessary usings 
- Create a function as  public  bulletcontroller GetBullet(Tanktype type) in the bullet service so that anyone can get a bullet when someone needs it and any type of bullet

2020-04-20 08:16 UTC, vijit101 reviewed
- Use scriptable objects in the model to transfer the data 
- Add extension functions to use and practice 
- Add enums for bullet types

2020-04-25 07:03 UTC, merged